version: '3'

networks:
  default:
    external:
      name: laravel

services:

  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - '4200:4200'
    depends_on:
      - backend
    volumes:
      - './frontend:/home/node/:cached'

  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - mysql
    volumes:
      - './backend:/var/www/html/:cached'
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30

  mysql:
    image: 'mariadb:10.4'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: huel
